import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'

//const inter = Inter({ subsets: ['latin'] })

const getData = async () =>  {
  const res= await axios.get("https://rickandmortyapi.com/api/character")
setRevalidateHeaders(res.)
}
export default function Home() {
  const [data, setdata] = useEstate([]);
  axios
  .
  return (
    <>
    <Head>
    <title>Rick and Morty API</title>
    <meta name="descripcion" content="Generated by create next app"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/> 
    <Link rel="icon" href="/favicon.ico"/>
     </Head>
   </>
  )
}
